name: Coleta e Análise de Dados

on:
  schedule:
    - cron: '0 12 * * *'  # Executa diariamente ao meio-dia
  workflow_dispatch:

jobs:
  scrape-and-analyze:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4 pandas numpy
        pip install scikit-learn
        
    - name: Run Scraper
      run: |
        python scripts/scraper.py
        python scripts/analyzer.py
        
    - name: Commit and Push Changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add data/predictions.json
        git commit -m "Atualização automática de previsões"
        git push
